### ISSUE TITLE
Random instances of websocket disconnects in jitsi

### ISSUE THREAD

**Issue by exalented** [jitsi/ice4j#251]
This issue has been around for a while. Our instance of jitsi connects more than three just fine, but after some time the websocket will become inactive and it takes a bit for us to hear one another again. This occurs with the latest images. What would cause the socket to close? Would it be caused by not having available resources (download more ram)?
```
org.jitsi.utils.logging2.LoggerImpl log
jitsi-jvb  | SEVERE: Error sending packet
jitsi-jvb  | java.io.IOException: No active socket.
jitsi-jvb  |    at org.ice4j.socket.MergingDatagramSocket.send(MergingDatagramSocket.java:202)
jitsi-jvb  |    at org.ice4j.socket.DelegatingDatagramSocket.send(DelegatingDatagramSocket.java:777)
jitsi-jvb  |    at org.jitsi.videobridge.transport.ice.IceTransport.send(IceTransport.kt:231)
jitsi-jvb  |    at org.jitsi.videobridge.Endpoint.doSendSrtp(Endpoint.kt:465)
jitsi-jvb  |    at org.jitsi.videobridge.Endpoint.access$doSendSrtp(Endpoint.kt:100)
jitsi-jvb  |    at org.jitsi.videobridge.Endpoint$outgoingSrtpPacketQueue$1.invoke(Endpoint.kt:178)
jitsi-jvb  |    at org.jitsi.videobridge.Endpoint$outgoingSrtpPacketQueue$1.invoke(Endpoint.kt:178)
jitsi-jvb  |    at org.jitsi.nlj.util.PacketInfoQueue._init_$lambda-0(PacketInfoQueue.kt:31)
jitsi-jvb  |    at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:381)
jitsi-jvb  |    at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:133)
jitsi-jvb  |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
jitsi-jvb  |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
jitsi-jvb  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jitsi-jvb  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jitsi-jvb  |    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Kirillbo** [comment]
I encountered a similar problem. We have more than two jvb bridges connected. After some time, this error appears on the connected bridges.

java.io.IOException: No active socket.
	at org.ice4j.socket.MergingDatagramSocket.send(MergingDatagramSocket.java:202)
	at org.ice4j.socket.DelegatingDatagramSocket.send(DelegatingDatagramSocket.java:777)
	at org.jitsi.videobridge.transport.ice.IceTransport.send(IceTransport.kt:245)
	at org.jitsi.videobridge.Endpoint.doSendSrtp(Endpoint.kt:552)
	at org.jitsi.videobridge.Endpoint.access$doSendSrtp(Endpoint.kt:113)
	at org.jitsi.videobridge.Endpoint$outgoingSrtpPacketQueue$1.invoke(Endpoint.kt:206)
	at org.jitsi.videobridge.Endpoint$outgoingSrtpPacketQueue$1.invoke(Endpoint.kt:206)
	at org.jitsi.nlj.util.PacketInfoQueue._init_$lambda$0(PacketInfoQueue.kt:31)
	at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
	at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
