### ISSUE TITLE
unresolved address error while harvesting STUN candidates

### ISSUE THREAD

**Issue by ajaychandra7888** [jitsi/ice4j#268]
While running IceDistributed , getting the following error:
Mar 04, 2023 1:18:14 PM org.ice4j.ice.harvest.StunCandidateHarvest sendRequest
INFO: Failed to send ALLOCATE-REQUEST(0x3)[attrib.count=3 len=32 tranID=0x26C197AB86016EEB5E36E9A6] through 172.17.84.152:2020/udp to stun6.jitsi.net:3478/udp
java.lang.IllegalArgumentException: unresolved address
	at java.base/java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:350)
	at java.base/java.net.DatagramPacket.<init>(DatagramPacket.java:157)
	at org.ice4j.stack.Connector.sendMessage(Connector.java:326)
	at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:634)
	at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:581)
	at org.ice4j.stack.StunClientTransaction.sendRequest0(StunClientTransaction.java:267)
	at org.ice4j.stack.StunClientTransaction.sendRequest(StunClientTransaction.java:245)
	at org.ice4j.stack.StunStack.sendRequest(StunStack.java:680)
	at org.ice4j.stack.StunStack.sendRequest(StunStack.java:618)
	at org.ice4j.ice.harvest.StunCandidateHarvest.sendRequest(StunCandidateHarvest.java:1300)
	at org.ice4j.ice.harvest.StunCandidateHarvest.startResolvingCandidate(StunCandidateHarvest.java:1405)
	at org.ice4j.ice.harvest.StunCandidateHarvester.startResolvingCandidate(StunCandidateHarvester.java:340)
	at org.ice4j.ice.harvest.StunCandidateHarvester.harvest(StunCandidateHarvester.java:252)
	at org.ice4j.ice.harvest.CandidateHarvesterSetElement.harvest(CandidateHarvesterSetElement.java:86)
	at org.ice4j.ice.harvest.CandidateHarvesterSetTask.run(CandidateHarvesterSetTask.java:107)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by nils-ohlmeier** [comment]
Indeed that DNS entry doesn't appear to exist any more. 
@aaronkvanmeerten @bgrozev any idea what happened here?

**Comment by ajaychandra7888** [comment]
it was an issue with the STUN/TURN servers URLs in Ice.java. (stun.jitsi.net:3478 not getting resolved)
tried with google's Stun server..it worked.
