### ISSUE TITLE
NoSuchFieldError: USE_PUSH_API

### ISSUE THREAD

**Issue by vsatmydynipnet** [jitsi/ice4j#295]
Hi,

I updated a friends Debian 12 box today which loaded Debian 12.8 and new Jitsi Packages from the stable Jitsi.org APT source.

After rebooting i get

```
JVB 2024-11-13 14:04:13.900 INFORMATION: [1] JitsiConfig.<clinit>#47: Initialized newConfig: merge of /etc/jitsi/videobridge/jvb.conf: 1,application.conf @ jar:[file:/usr/share/jitsi-videobridge/j](file:///usr/share/jitsi-videobridge/j)
itsi-videobridge.jar!/application.conf: 1,system properties,reference.conf @ [jar:file:/usr/share/jitsi-videobridge/jitsi-videobridge.jar!/reference.conf](jar:file:///usr/share/jitsi-videobridge/jitsi-videobridge.jar!/reference.conf): 1,reference.conf @ jar:[file:/usr/share/ji](file:///usr/share/ji)
tsi-videobridge/lib/jitsi-media-transform-2.3-174-gd011ddf7.jar!/reference.conf: 1,reference.conf @ [jar:file:/usr/share/jitsi-videobridge/lib/jitsi-media-transform-1.0-261-g7b0aeed.jar!/reference](jar:file:///usr/share/jitsi-videobridge/lib/jitsi-media-transform-1.0-261-g7b0aeed.jar!/reference)
.conf: 1,reference.conf @ [jar:file:/usr/share/jitsi-videobridge/lib/ice4j-3.0-35-gadca67b.jar!/reference.conf](jar:file:///usr/share/jitsi-videobridge/lib/ice4j-3.0-35-gadca67b.jar!/reference.conf): 1,reference.conf @ jar:[file:/usr/share/jitsi-videobridge/lib/ice4j-3.2-4-g1373788.ja](file:///usr/share/jitsi-videobridge/lib/ice4j-3.2-4-g1373788.ja)
r!/reference.conf: 1
JVB 2024-11-13 14:04:13.917 INFORMATION: [1] ReadOnlyConfigurationService.reloadConfiguration#51: loading config file at path /etc/jitsi/videobridge/sip-communicator.properties
JVB 2024-11-13 14:04:13.919 INFORMATION: [1] JitsiConfig.<clinit>#68: Initialized legacyConfig: sip communicator props (no description provided)
JVB 2024-11-13 14:04:14.162 INFORMATION: [1] JvmMetrics.<init>#36: Detected GC type G1
JVB 2024-11-13 14:04:14.169 INFORMATION: [1] MetricsUpdater.addUpdateTask#45: Scheduling metrics update task with interval PT5S.
JVB 2024-11-13 14:04:14.184 INFORMATION: [1] JitsiConfig$Companion.reloadNewConfig#94: Reloading the Typesafe config source (previously reloaded 0 times).
JVB 2024-11-13 14:04:14.199 INFORMATION: [1] MainKt.main#81: Starting jitsi-videobridge version 2.3.174-gd011ddf7
JVB 2024-11-13 14:04:14.215 INFORMATION: [1] UlimitCheck.printUlimits#109: Running with open files limit 65000 (hard 65000), thread limit 65000 (hard 65000).
JVB 2024-11-13 14:04:14.216 SCHWERWIEGEND: [1] MainKt.main$lambda$0#60: An uncaught exception occurred in thread=Thread[main,5,main]
java.lang.NoSuchFieldError: USE_PUSH_API
        at org.jitsi.videobridge.MainKt.startIce4j(Main.kt:227)
        at org.jitsi.videobridge.MainKt.main(Main.kt:84)
        at org.jitsi.videobridge.MainKt.main(Main.kt)
```

I restore Proxmox Snapshot so he cann use Jitsi again, but I am looking for a solution to the above to keep his system updated.

Any hints, even temporary workarounds are greatly appreciated.

Thank you.

**Comment by damencho** [comment]
You have several ice4j in your folder:
/usr/share/jitsi-videobridge/lib/ice4j-3.0-35-gadca67b.jar
/usr/share/jitsi-videobridge/lib/ice4j-3.2-4-g1373788.jar
The latest jvb stable builds come with https://github.com/jitsi/jitsi-videobridge/blob/cc337a2abe033a4a2785ee6ef6f0303c1ca2fc9a/pom.xml#L109 
Drop the other one.

Please, when you have questions or problems use the community forum before opening new issues, thank you.
